<div class="product wo_jobs_list" id="product-<?php echo $wo['job']['id']?>" data-id="<?php echo $wo['job']['id']?>">
	<div class="wo_jlist_headimg">
		<a href="<?php echo $wo['job']['url']?>"><img src="<?php echo Wo_GetMedia($wo['job']['image']);?>"></a>
	</div>
	<div class="wo_jlist_info">
		<div class="wo_jlist_info_head" style="display: block;">
			<h2 style="display: inline-block;"><a href="<?php echo $wo['job']['url']?>" title="<?php echo $wo['job']['title']?>"><?php echo $wo['job']['title']?></a></h2>
			<div style="float: right;">
				<?php if (Wo_IsModerator() || Wo_IsAdmin()) { ?>
					<a class="btn btn-main" href="javascript:void(0)" onclick="Wo_OpenJobDeleteBox(<?php echo  $wo['job']['id']; ?>);"><?php echo $wo['lang']['delete'] ?></a>
				<?php } ?>
			    <a class="btn btn-main" href="<?php echo $wo['job']['url']?>"><?php echo $wo['lang']['apply_now'] ?></a>
			</div>
		</div>
		<div class="wo_jlist_info_main">
			<span><?php echo (!empty($wo['currencies'][$wo['config']['currency']]['symbol'])) ? $wo['currencies'][$wo['config']['currency']]['symbol'] : $wo['config']['classified_currency_s'];?><?php echo $wo['job']['minimum']?> - <?php echo (!empty($wo['currencies'][$wo['config']['currency']]['symbol'])) ? $wo['currencies'][$wo['config']['currency']]['symbol'] : $wo['config']['classified_currency_s'];?><?php echo $wo['job']['maximum']?></span>
			<span class="middot">·</span>
			<?php
				$product_by_ = $wo['job']['category'];
				$product_by_ = str_replace('{product_category_name}', $wo['job_categories'][$wo['job']['category']], $product_by_);
			?>
			<span><a href="<?php echo Wo_SeoLink('index.php?link1=jobs');?>?c_id=<?php echo($wo['job']['category']) ?>"><?php echo $wo['job_categories'][$wo['job']['category']];?></a></span>
		</div>
		<p><?php echo mb_substr($wo['job']['description'], 0, 150, "UTF-8") . '...';?></p>
	</div>
	<div class="clear"></div>
</div>